### PR TITLE
Merge Team 1 fix into Team 3 main repo

### PR DESCRIPTION
**Pull request by AnthonyLiu-Git**

### CODE REVIEW

**Review by michaelko92 — APPROVED** [review]
All tests passing. No merge conflicts. Good to go

**Review by scduffy — APPROVED** [review]
cool

**Review by Russell-Nesbitt — APPROVED** [review]
Fixed all my methods properly.

**Comment by bbshash** [comment]
Looks good

**Review by bbshash — APPROVED** [review]
Looks good and fixed my methods properly

**Pull request merged**
